### ISSUE TITLE
Loss_ER is too small. Is it really helpful?

### ISSUE THREAD

**Issue by zzzzzz0407** [YudeWang/SEAM#1]
![image](https://user-images.githubusercontent.com/27133144/79973177-aa610780-84c9-11ea-977c-14f369b280e1.png)
Thanks for your wonderful job. 
However, when I read your code, I find that the loss_er is too small compared with other two loss. The reason is that you apply mean operation directly, however, there are a lot of 0(you set 0 for C-1 channels). 
![image](https://user-images.githubusercontent.com/27133144/79974230-830b3a00-84cb-11ea-8751-ffaecec9baad.png)
And I find the improvement within loss_er is much small in your paper compared with loss_ecr, I argue this may a bug?
![image](https://user-images.githubusercontent.com/27133144/79974324-b221ab80-84cb-11ea-9c23-9d0280ee3391.png)
I am sorry I do not have enough gpus to reproduce it.
Look forward to your reply

**Comment by YudeWang** [comment]
Hi @zzzzzz0407, thanks for your suggestion. Before coming to the idea of PCM, I have noticed this and fixed it. However, I find there should be a small weight for `loss_er` to learn, or the results are not good enough. Therefore, I roll back to the old version as you see, which looks like a negligence but works, and do not need to set a weight parameter for `loss_er`. It is a good idea to verify whether `loss_er' is necessary when SEAM have `loss_ecr`. I would like to do some experiments later (my server is down and I cannot back to my work due to the city restriction for COVID-19).

**Comment by zzzzzz0407** [comment]
Thanks for your reply.
